title: ゼロから作らない ChatGPT
description: 本サイトでは ChatGPT の基盤となる要素技術を解説します．
author: Hirokazu Kiyomaru
email: 'h.kiyomaru@gmail.com'
url: https://hkiyomaru.github.io/chat-gpt-not-from-scratch/
markdown: kramdown

theme: minima
